import { useEffect, useState } from 'react'
import { icons, Icon } from './shared'
import GrowthIntelligenceView from './analytics/GrowthIntelligenceView'
import SettingsPage from './settings/SettingsPage'
import SecurityPage from './security/SecurityPage'
import { AdminGate, LiveOverview, LiveUsers, LiveMentors, LivePaths, AdminHeader } from './liveAdmin'
import { requireAdmin } from './lib/supabase'

type Page='overview'|'users'|'paths'|'mentors'|'analytics'|'settings'|'security'
function Shell({page,setPage,profile}:{page:Page,setPage:(p:Page)=>void,profile:any}){
 const sections=[['MAIN',[['overview','Overview','overview'],['users','Users','users'],['paths','Growth Paths','paths'],['mentors','Mentors','mentors']]],['INSIGHTS',[['analytics','Analytics','analytics']]],['SYSTEM',[['security','Security','shieldCheck'],['settings','Settings','settings']]]] as const
 return <div style={{display:'flex',minHeight:'100vh',background:'#FAF8F4',color:'#171717',fontFamily:'Inter,system-ui,sans-serif'}}><aside style={{width:272,minWidth:272,background:'linear-gradient(180deg,#FFFDF8 0%,#FAF5EC 100%)',borderRight:'1px solid #E8D9B5',display:'flex',flexDirection:'column',height:'100vh',position:'sticky',top:0}}><div style={{padding:'24px 20px',borderBottom:'1px solid #E8D9B5'}}><div style={{display:'flex',alignItems:'center',gap:12}}><div style={{width:36,height:36,background:'#111',borderRadius:10,display:'grid',placeItems:'center'}}><Icon d={icons.star} size={18} style={{color:'#C89B1E'}}/></div><div><div style={{fontFamily:'Playfair Display,serif',fontWeight:600,fontSize:20}}>Starfix</div><div style={{fontSize:11,color:'#6F6F6F'}}>Growth Operations</div></div></div></div><nav style={{flex:1,padding:'20px 14px',display:'flex',flexDirection:'column',gap:20}}>{sections.map(([title,items])=><div key={title}><div style={{fontSize:10.5,fontWeight:600,color:'#A09886',letterSpacing:'.08em',padding:'0 12px 6px'}}>{title}</div>{items.map(([id,label,icon])=><button key={id} onClick={()=>setPage(id as Page)} style={{display:'flex',alignItems:'center',gap:14,width:'100%',height:46,padding:'0 14px',borderRadius:14,border:0,cursor:'pointer',background:page===id?'#F7EFD8':'transparent',color:page===id?'#111':'#6F6F6F',fontSize:14,fontWeight:page===id?600:500,textAlign:'left'}}><Icon d={icons[icon as keyof typeof icons]} size={17} style={{color:page===id?'#C89B1E':'#8E8E93'}}/>{label}</button>)}</div>)}</nav><div style={{padding:14,borderTop:'1px solid #E8D9B5'}}><div style={{fontSize:12,fontWeight:600}}>{profile?.full_name||'Administrator'}</div><div style={{fontSize:11,color:'#737373',marginTop:2}}>{profile?.email}</div></div></aside><div style={{flex:1,minWidth:0}}><AdminHeader profile={profile}/><main>{page==='overview'&&<LiveOverview/>}{page==='users'&&<LiveUsers/>}{page==='paths'&&<LivePaths/>}{page==='mentors'&&<LiveMentors/>}{page==='analytics'&&<GrowthIntelligenceView/>}{page==='security'&&<SecurityPage/>}{page==='settings'&&<SettingsPage/>}</main></div></div>
}
export default function App(){ const [profile,setProfile]=useState<any>(null); const [page,setPage]=useState<Page>('overview'); useEffect(()=>{requireAdmin().then(r=>setProfile(r.profile))},[]); return <AdminGate><Shell page={page} setPage={setPage} profile={profile}/></AdminGate> }
