import{useEffect,useMemo,useState}from'react'
import{Card,PageShell}from'./shared'
import{getAdminOverview,getAdminUsers,getAdminMentors,getAdminPaths,getAdminBookings,getAdminExplore,getAdminConversations,getAdminAnalytics,type AdminUser,type AdminMentor}from'./adminBackend'
import{signIn,signOutAdmin,requireAdmin}from'./lib/supabase'

const btn={padding:'8px 13px',border:'1px solid #E8D9B5',borderRadius:8,background:'#FFFDF8',cursor:'pointer',fontSize:12.5,color:'#171717'}
const th={textAlign:'left' as const,padding:12,fontSize:11,color:'#8E8E93',background:'#FAF8F4'}
const td={padding:13,borderTop:'1px solid #ECE7DF'}

export function AdminGate({children}:{children:React.ReactNode}){const[state,setState]=useState<'loading'|'login'|'ok'>('loading'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{requireAdmin().then(r=>{setState(r.profile?'ok':'login');if(r.error&&r.error.message!=='Not signed in')setError(r.error.message)}).catch(()=>setState('login'))},[]);if(state==='loading')return <div style={{minHeight:'100vh',display:'grid',placeItems:'center',background:'#080808',color:'#D4AF37'}}>Checking administrator access…</div>;if(state==='login')return <div style={{minHeight:'100vh',display:'grid',placeItems:'center',background:'#080808'}}><Card style={{width:390,padding:32,background:'#111',borderColor:'#3A2D0D',color:'#fff'}}><div style={{fontFamily:'Playfair Display,serif',fontSize:27}}>Starfix Admin</div><div style={{color:'#A7A7A7',fontSize:13,margin:'7px 0 24px'}}>Growth Operations · Administrator sign in</div>{error&&<div style={{background:'#351414',color:'#FCA5A5',padding:10,borderRadius:8,fontSize:12,marginBottom:14}}>{error}</div>}<input value={email}onChange={e=>setEmail(e.target.value)}placeholder="Admin email"type="email"style={{width:'100%',boxSizing:'border-box',padding:11,border:'1px solid #3A3A3A',background:'#181818',color:'#fff',borderRadius:8,marginBottom:10}}/><input value={password}onChange={e=>setPassword(e.target.value)}placeholder="Password"type="password"onKeyDown={e=>{if(e.key==='Enter')document.getElementById('admin-login')?.click()}}style={{width:'100%',boxSizing:'border-box',padding:11,border:'1px solid #3A3A3A',background:'#181818',color:'#fff',borderRadius:8}}/><button id="admin-login"disabled={busy}onClick={async()=>{setBusy(true);setError('');try{await signIn(email,password);const r=await requireAdmin();if(r.error)throw r.error;setState('ok')}catch(e){setError(e instanceof Error?e.message:'Sign in failed');await signOutAdmin()}finally{setBusy(false)}}}style={{width:'100%',marginTop:16,padding:12,border:0,borderRadius:9,background:'#D4AF37',color:'#080808',fontWeight:700}}>{busy?'Signing in…':'Sign in as administrator'}</button></Card></div>;return <>{children}</>}

function Stat({label,value,detail}:{label:string,value:string|number,detail:string}){return <Card style={{padding:20}}><div style={{fontSize:11,color:'#8E8E93',textTransform:'uppercase'}}>{label}</div><div style={{fontFamily:'Playfair Display,serif',fontSize:29,fontWeight:600,marginTop:8}}>{value}</div><div style={{fontSize:11.5,color:'#737373',marginTop:6}}>{detail}</div></Card>}

function DataTable({children}:{children:React.ReactNode}){return <Card style={{padding:0,overflow:'hidden'}}><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}>{children}</table></div></Card>}

export function LiveOverview(){const[d,setD]=useState<any>(null),[err,setErr]=useState('');useEffect(()=>{getAdminOverview().then(setD).catch(e=>setErr(e.message))},[]);if(err)return <PageShell title="Overview"subtitle="Live Starfix operations."><Card style={{padding:24,color:'#991B1B'}}>{err}</Card></PageShell>;if(!d)return <PageShell title="Overview"subtitle="Live Starfix operations."><Card style={{padding:24}}>Loading live Starfix data…</Card></PageShell>;return <PageShell title="Starfix Overview"subtitle="Live operational data from the Starfix Supabase database."><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:16,marginBottom:22}}><Stat label="Learners"value={d.learners}detail={d.activeLearners+' active in last 7 days'}/><Stat label="Mentors"value={d.mentors}detail="Mentor profiles"/><Stat label="Bookings"value={d.bookings}detail="Total mentor bookings"/><Stat label="Growth Paths"value={d.paths}detail={d.completedPaths+' completed progress records'}/></div><DataTable><thead><tr>{['Mentor','Session','Status','Scheduled','Amount'].map(h=><th key={h}style={th}>{h}</th>)}</tr></thead><tbody>{d.recentBookings.length?d.recentBookings.map((b:any)=><tr key={b.id}><td style={td}>{b.mentor_name||'Mentor'}</td><td style={td}>{b.session_type||'Mentoring session'}</td><td style={td}>{b.status||'—'}</td><td style={td}>{b.scheduled_start?new Date(b.scheduled_start).toLocaleString():'—'}</td><td style={td}>₹{Number(b.amount||0).toLocaleString()}</td></tr>):<tr><td colSpan={5}style={{padding:28,textAlign:'center',color:'#8E8E93'}}>No bookings yet — new genuine Starfix bookings will appear here automatically.</td></tr>}</tbody></DataTable></PageShell>}

export function LiveUsers(){const[users,setUsers]=useState<AdminUser[]>([]),[q,setQ]=useState(''),[filter,setFilter]=useState('All'),[err,setErr]=useState('');useEffect(()=>{getAdminUsers().then(setUsers).catch(e=>setErr(e.message))},[]);const rows=useMemo(()=>users.filter(u=>(filter==='All'||u.status===filter)&&((u.name+' '+u.email+' '+u.path).toLowerCase().includes(q.toLowerCase()))),[users,q,filter]);return <PageShell title="Learners Directory"subtitle="Real students, profile goals, live progress, XP and activity."><div style={{display:'flex',gap:10,marginBottom:16,flexWrap:'wrap'}}><input value={q}onChange={e=>setQ(e.target.value)}placeholder="Search name, email or path…"style={{flex:1,maxWidth:360,padding:10,border:'1px solid #E8E0D3',borderRadius:8}}/>{['All','Active','At risk','Inactive'].map(x=><button key={x}onClick={()=>setFilter(x)}style={{...btn,background:filter===x?'#171717':'#FFFDF8',color:filter===x?'#fff':'#171717'}}>{x}</button>)}</div>{err?<Card style={{padding:20,color:'#991B1B'}}>{err}</Card>:<DataTable><thead><tr>{['Learner','Goal','Active Path','Progress','Streak','XP','Status'].map(h=><th key={h}style={th}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map(u=><tr key={u.id}><td style={td}><b>{u.name}</b><div style={{fontSize:11,color:'#8E8E93'}}>{u.email}</div></td><td style={td}>{u.goal||'—'}</td><td style={td}>{u.path}</td><td style={td}>{u.progress}%</td><td style={td}>{u.streak} 🔥</td><td style={td}>{u.xp.toLocaleString()}</td><td style={td}>{u.status}</td></tr>):<tr><td colSpan={7}style={{padding:28,textAlign:'center',color:'#8E8E93'}}>No learners match the current filter.</td></tr>}</tbody></DataTable>}</PageShell>}

export function LiveMentors(){const[rows,setRows]=useState<AdminMentor[]>([]),[q,setQ]=useState(''),[err,setErr]=useState('');useEffect(()=>{getAdminMentors().then(setRows).catch(e=>setErr(e.message))},[]);const filtered=rows.filter(m=>(m.name+' '+(m.email||'')+' '+(m.company||'')+' '+(m.category||'')).toLowerCase().includes(q.toLowerCase()));return <PageShell title="Mentors"subtitle="Live mentor profiles, onboarding, availability and learner capacity."><input value={q}onChange={e=>setQ(e.target.value)}placeholder="Search mentors…"style={{width:320,padding:10,border:'1px solid #E8E0D3',borderRadius:8,marginBottom:16}}/>{err?<Card style={{padding:20,color:'#991B1B'}}>{err}</Card>:<DataTable><thead><tr>{['Mentor','Role / Company','Category','Rating','Learners','Availability','Onboarding'].map(h=><th key={h}style={th}>{h}</th>)}</tr></thead><tbody>{filtered.map(m=><tr key={m.id}><td style={td}><b>{m.name}</b><div style={{fontSize:11,color:'#8E8E93'}}>{m.email||'No email'}</div></td><td style={td}>{m.headline||'—'}{m.company?' · '+m.company:''}</td><td style={td}>{m.category||'—'}</td><td style={td}>★ {m.rating.toFixed(1)}</td><td style={td}>{m.students}</td><td style={td}>{m.availability||'—'}</td><td style={td}>{m.onboarding?'Complete':'Pending'}</td></tr>)}</tbody></DataTable>}</PageShell>}

export function LivePaths(){const[rows,setRows]=useState<any[]>([]),[err,setErr]=useState('');useEffect(()=>{getAdminPaths().then(setRows).catch(e=>setErr(e.message))},[]);return <PageShell title="Growth Paths"subtitle="Live paths, milestones and learner progress."><DataTable>{err?<tbody><tr><td style={{padding:20,color:'#991B1B'}}>{err}</td></tr></tbody>:<><thead><tr>{['Path','Category','Level','Milestones','Learners','Avg Progress','Rating'].map(h=><th key={h}style={th}>{h}</th>)}</tr></thead><tbody>{rows.map(p=><tr key={p.id}><td style={td}><b>{p.title}</b><div style={{fontSize:11,color:'#8E8E93'}}>{p.slug}</div></td><td style={td}>{p.category||'—'}</td><td style={td}>{p.level||'—'}</td><td style={td}>{p.milestoneCount}</td><td style={td}>{p.liveLearners}</td><td style={td}>{p.completion}%</td><td style={td}>★ {Number(p.rating||0).toFixed(1)}</td></tr>)}</tbody></>}</DataTable></PageShell>}

export function LiveBookings(){const[rows,setRows]=useState<any[]>([]),[q,setQ]=useState(''),[err,setErr]=useState('');useEffect(()=>{getAdminBookings().then(setRows).catch(e=>setErr(e.message))},[]);const filtered=rows.filter(b=>(b.mentor_name+' '+b.status+' '+b.session_type+' '+b.booking_date).toLowerCase().includes(q.toLowerCase()));return <PageShell title="Sessions & Bookings"subtitle="Every real Starfix mentor booking from Supabase, newest scheduled sessions first."><input value={q}onChange={e=>setQ(e.target.value)}placeholder="Search mentor, status, session…"style={{width:360,padding:10,border:'1px solid #E8E0D3',borderRadius:8,marginBottom:16}}/>{err?<Card style={{padding:20,color:'#991B1B'}}>{err}</Card>:<DataTable><thead><tr>{['Student ID','Mentor','Session','Date / Time','Status','Amount','Notes'].map(h=><th key={h}style={th}>{h}</th>)}</tr></thead><tbody>{filtered.length?filtered.map(b=><tr key={b.id}><td style={td}>{b.student_id?.slice(0,8)||'—'}…</td><td style={td}><b>{b.mentor_name||'—'}</b><div style={{fontSize:11,color:'#8E8E93'}}>{b.mentor_company||''}</div></td><td style={td}>{b.session_type||'—'}<div style={{fontSize:11,color:'#8E8E93'}}>{b.duration||''}</div></td><td style={td}>{b.scheduled_start?new Date(b.scheduled_start).toLocaleString():b.booking_date||'—'}</td><td style={td}>{b.status||'—'}</td><td style={td}>₹{Number(b.amount||0).toLocaleString()}</td><td style={td}>{b.notes||'—'}</td></tr>):<tr><td colSpan={7}style={{padding:28,textAlign:'center',color:'#8E8E93'}}>No bookings yet. The table will populate from genuine student bookings.</td></tr>}</tbody></DataTable>}</PageShell>}

export function LiveExplore(){const[rows,setRows]=useState<any[]>([]),[q,setQ]=useState('');useEffect(()=>{getAdminExplore().then(setRows).catch(()=>setRows([]))},[]);const filtered=rows.filter(x=>(x.title+' '+x.category+' '+x.content_type).toLowerCase().includes(q.toLowerCase()));return <PageShell title="Explore Content"subtitle="Real Explore resources currently stored in Starfix."><input value={q}onChange={e=>setQ(e.target.value)}placeholder="Search content…"style={{width:320,padding:10,border:'1px solid #E8E0D3',borderRadius:8,marginBottom:16}}/><DataTable><thead><tr>{['Title','Category','Type','Metric','Active','Created'].map(h=><th key={h}style={th}>{h}</th>)}</tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td style={td}><b>{x.title}</b><div style={{fontSize:11,color:'#8E8E93'}}>{x.description||''}</div></td><td style={td}>{x.category}</td><td style={td}>{x.content_type}</td><td style={td}>{x.metric_value||'—'}</td><td style={td}>{x.active?'Active':'Hidden'}</td><td style={td}>{x.created_at?new Date(x.created_at).toLocaleDateString():'—'}</td></tr>)}</tbody></DataTable></PageShell>}

export function LiveMessages(){const[rows,setRows]=useState<any[]>([]);useEffect(()=>{getAdminConversations().then(setRows).catch(()=>setRows([]))},[]);return <PageShell title="Mentor Conversations"subtitle="Operational view of real mentor-student conversations and recent messages."><DataTable><thead><tr>{['Conversation','Student ID','Mentor ID','Messages','Last activity','Archived'].map(h=><th key={h}style={th}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map(c=><tr key={c.id}><td style={td}>{c.id.slice(0,8)}…</td><td style={td}>{c.student_id?.slice(0,8)}…</td><td style={td}>{c.mentor_id?.slice(0,8)}…</td><td style={td}>{c.messages?.length||0}<div style={{fontSize:11,color:'#8E8E93'}}>{c.messages?.[0]?.body?.slice(0,50)||'No messages'}</div></td><td style={td}>{c.messages?.[0]?.created_at?new Date(c.messages[0].created_at).toLocaleString():new Date(c.created_at).toLocaleString()}</td><td style={td}>{c.archived?'Yes':'No'}</td></tr>):<tr><td colSpan={6}style={{padding:28,textAlign:'center',color:'#8E8E93'}}>No conversations yet.</td></tr>}</tbody></DataTable></PageShell>}

export function LiveAnalytics(){const[d,setD]=useState<any>(null);useEffect(()=>{getAdminAnalytics().then(setD).catch(()=>setD({}))},[]);if(!d)return <PageShell title="Analytics"subtitle="Live Starfix metrics."><Card>Loading live analytics…</Card></PageShell>;return <PageShell title="Analytics"subtitle="Calculated directly from current Starfix database records."><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:16}}>{[['Students',d.students,'Registered student profiles'],['Mentors',d.mentors,'Mentor profiles'],['Active 7d',d.active7,'Learners with recent activity'],['Progress',d.avgProgress+'%','Average progress'],['Completed',d.completed,'Completed progress records'],['Total XP',d.totalXp.toLocaleString(),'Across progress records'],['Bookings',d.bookings,d.confirmed+' confirmed/completed'],['Revenue','₹'+d.revenue.toLocaleString(),'Booking amount total'],['Reviews',d.reviews,'Average '+d.avgRating+'★'],['Saved Items',d.saved,'Learner saved resources'],['Notifications',d.notifications,'Notifications generated'],['Admins',d.admins,'Admin profiles']].map(([a,b,c])=><Stat key={String(a)}label={String(a)}value={b as any}detail={String(c)}/>)}</div></PageShell>}

export function AdminHeader({profile}:{profile:any}){return <div style={{height:68,borderBottom:'1px solid #E8D9B5',background:'#FFFDF8',display:'flex',alignItems:'center',justifyContent:'flex-end',padding:'0 26px',gap:12}}><div style={{fontSize:12,color:'#737373'}}>{profile?.full_name||profile?.email}</div><button style={btn}onClick={()=>signOutAdmin().then(()=>location.reload())}>Sign out</button></div>}
