import { useEffect, useMemo, useState } from 'react'
import { Icon, icons, Card, PageShell } from './shared'
import { getAdminOverview, getAdminUsers, getAdminMentors, getAdminPaths, signOutAdmin, type AdminUser, type AdminMentor } from './adminBackend'
import { supabase, requireAdmin } from './lib/supabase'

const btn={padding:'8px 13px',border:'1px solid #E8D9B5',borderRadius:8,background:'#FFFDF8',cursor:'pointer',fontSize:12.5,color:'#171717'}
const gold='#C89B1E'

export function AdminGate({children}:{children:React.ReactNode}){
 const [state,setState]=useState<'loading'|'login'|'ok'>('loading'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
 useEffect(()=>{requireAdmin().then(r=>{setState(r.profile?'ok':'login');if(r.error&&r.error.message!=='Not signed in')setError(r.error.message)})},[])
 if(state==='loading') return <div style={{minHeight:'100vh',display:'grid',placeItems:'center',background:'#FAF8F4',fontFamily:'Inter,sans-serif'}}>Checking administrator access…</div>
 if(state==='login') return <div style={{minHeight:'100vh',display:'grid',placeItems:'center',background:'linear-gradient(135deg,#FAF8F4,#FFFDF8)',fontFamily:'Inter,sans-serif'}}><Card style={{width:390,padding:32}}><div style={{fontFamily:'Playfair Display,serif',fontSize:27,fontWeight:600}}>Starfix Admin</div><div style={{color:'#737373',fontSize:13,margin:'7px 0 24px'}}>Growth Operations · Administrator sign in</div>{error&&<div style={{background:'#FFF1F2',color:'#991B1B',padding:10,borderRadius:8,fontSize:12,marginBottom:14}}>{error}</div>}<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Admin email" type="email" style={{width:'100%',boxSizing:'border-box',padding:11,border:'1px solid #DDD5C7',borderRadius:8,marginBottom:10}}/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" type="password" onKeyDown={e=>{if(e.key==='Enter')document.getElementById('admin-login')?.click()}} style={{width:'100%',boxSizing:'border-box',padding:11,border:'1px solid #DDD5C7',borderRadius:8}}/><button id="admin-login" disabled={busy} onClick={async()=>{setBusy(true);setError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error){setError(error.message);setBusy(false);return}const r=await requireAdmin();if(r.error){setError(r.error.message);await supabase.auth.signOut()}else setState('ok');setBusy(false)}} style={{width:'100%',marginTop:16,padding:12,border:0,borderRadius:9,background:'#171717',color:'#fff',fontWeight:600,cursor:'pointer'}}>{busy?'Signing in…':'Sign in as administrator'}</button><div style={{fontSize:11,color:'#8E8E93',marginTop:16,lineHeight:1.5}}>Only a Supabase account whose Starfix profile has the admin role can access this dashboard.</div></Card></div>
 return <>{children}</>
}

function Stat({label,value,detail}:{label:string,value:string|number,detail:string}){return <Card style={{padding:20}}><div style={{fontSize:11,color:'#8E8E93',textTransform:'uppercase',letterSpacing:'.05em'}}>{label}</div><div style={{fontFamily:'Playfair Display,serif',fontSize:29,fontWeight:600,marginTop:8}}>{value}</div><div style={{fontSize:11.5,color:'#737373',marginTop:6}}>{detail}</div></Card>}

export function LiveOverview(){
 const [d,setD]=useState<any>(null); const [err,setErr]=useState(''); useEffect(()=>{getAdminOverview().then(setD).catch(e=>setErr(e.message))},[])
 if(err)return <PageShell title="Overview" subtitle="Live Starfix operations"><Card style={{padding:24,color:'#991B1B'}}>Could not load live data: {err}</Card></PageShell>
 if(!d)return <PageShell title="Overview" subtitle="Live Starfix operations"><Card style={{padding:24}}>Loading live Starfix data…</Card></PageShell>
 const confirmed=d.recentBookings.filter((b:any)=>['confirmed','completed'].includes(b.status)).length
 return <PageShell title="Starfix Overview" subtitle="Live operational data from the Starfix Supabase database."><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:16,marginBottom:22}}><Stat label="Learners" value={d.learners} detail={d.activeLearners+' active in the last 7 days'}/><Stat label="Mentors" value={d.mentors} detail="Mentor profiles in Starfix"/><Stat label="Bookings" value={d.bookings} detail={confirmed+' confirmed/completed in recent activity'}/><Stat label="Growth Paths" value={d.paths} detail={d.completedPaths+' completed progress records'}/></div><Card style={{padding:0,overflow:'hidden'}}><div style={{padding:'20px 22px',borderBottom:'1px solid #ECE7DF'}}><div style={{fontFamily:'Playfair Display,serif',fontSize:17,fontWeight:600}}>Recent Mentor Sessions</div><div style={{fontSize:12,color:'#737373',marginTop:3}}>Pulled directly from bookings — no demo rows.</div></div><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Mentor','Session','Status','Scheduled','Amount'].map(h=><th key={h} style={{textAlign:'left',padding:'11px 20px',fontSize:11,color:'#8E8E93',textTransform:'uppercase'}}>{h}</th>)}</tr></thead><tbody>{d.recentBookings.map((b:any)=><tr key={b.id} style={{borderTop:'1px solid #F0ECE5'}}><td style={{padding:'13px 20px',fontWeight:600,fontSize:13}}>{b.mentor_name||'Mentor'}</td><td style={{padding:'13px 20px',fontSize:13}}>{b.session_type||'Mentoring session'}</td><td style={{padding:'13px 20px'}}><span style={{background:'#F7F2E7',color:gold,padding:'4px 8px',borderRadius:6,fontSize:11}}>{b.status}</span></td><td style={{padding:'13px 20px',fontSize:12,color:'#737373'}}>{b.scheduled_start?new Date(b.scheduled_start).toLocaleString():'—'}</td><td style={{padding:'13px 20px',fontSize:13}}>₹{Number(b.amount||0).toLocaleString()}</td></tr>)}</tbody></table></div></Card></PageShell>
}

export function LiveUsers(){
 const [users,setUsers]=useState<AdminUser[]>([]); const [q,setQ]=useState(''); const [filter,setFilter]=useState('All'); const [loading,setLoading]=useState(true); const [err,setErr]=useState('')
 useEffect(()=>{getAdminUsers().then(setUsers).catch(e=>setErr(e.message)).finally(()=>setLoading(false))},[])
 const rows=useMemo(()=>users.filter(u=>(filter==='All'||u.status===filter)&&((u.name+' '+u.email+' '+u.path).toLowerCase().includes(q.toLowerCase()))),[users,q,filter])
 return <PageShell title="Learners Directory" subtitle="Real students registered in Starfix, with live path progress, XP and activity."><div style={{display:'flex',gap:10,marginBottom:16}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, email or path…" style={{flex:1,maxWidth:360,padding:10,border:'1px solid #E8E0D3',borderRadius:8}}/>{['All','Active','At risk','Inactive'].map(x=><button key={x} onClick={()=>setFilter(x)} style={{...btn,background:filter===x?'#171717':'#FFFDF8',color:filter===x?'#fff':'#171717'}}>{x}</button>)}</div>{err?<Card style={{padding:20,color:'#991B1B'}}>{err}</Card>:<Card style={{padding:0,overflow:'hidden'}}><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Learner','Goal','Active Path','Progress','Streak','XP','Status'].map(h=><th key={h} style={{textAlign:'left',padding:'12px 18px',fontSize:11,color:'#8E8E93',textTransform:'uppercase',background:'#FAF8F4'}}>{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={7} style={{padding:24}}>Loading…</td></tr>:rows.map(u=><tr key={u.id} style={{borderTop:'1px solid #ECE7DF'}}><td style={{padding:'13px 18px'}}><div style={{fontWeight:600,fontSize:13}}>{u.name}</div><div style={{fontSize:11.5,color:'#8E8E93'}}>{u.email}</div></td><td style={{padding:'13px 18px',fontSize:12.5}}>{u.goal||'—'}</td><td style={{padding:'13px 18px',fontSize:12.5}}>{u.path}</td><td style={{padding:'13px 18px',fontSize:12.5,fontWeight:600}}>{u.progress}%</td><td style={{padding:'13px 18px'}}>{u.streak} 🔥</td><td style={{padding:'13px 18px'}}>{u.xp.toLocaleString()}</td><td style={{padding:'13px 18px'}}><span style={{fontSize:11,color:u.status==='Active'?'#166534':u.status==='At risk'?'#92400E':'#737373',background:u.status==='Active'?'#F0FDF4':u.status==='At risk'?'#FFFBEB':'#F5F5F4',padding:'4px 8px',borderRadius:6}}>{u.status}</span></td></tr>)}</tbody></table></div></Card>}</PageShell>
}

export function LiveMentors(){
 const [rows,setRows]=useState<AdminMentor[]>([]); const [q,setQ]=useState(''); const [err,setErr]=useState('')
 useEffect(()=>{getAdminMentors().then(setRows).catch(e=>setErr(e.message))},[])
 const filtered=rows.filter(m=>(m.name+' '+(m.email||'')+' '+(m.company||'')+' '+(m.category||'')).toLowerCase().includes(q.toLowerCase()))
 return <PageShell title="Mentors" subtitle="Live mentor profiles, onboarding and learner capacity from Starfix."><div style={{display:'flex',gap:10,marginBottom:16}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search mentors…" style={{width:320,padding:10,border:'1px solid #E8E0D3',borderRadius:8}}/></div>{err?<Card style={{padding:20,color:'#991B1B'}}>{err}</Card>:<Card style={{padding:0,overflow:'hidden'}}><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Mentor','Role / Company','Category','Rating','Learners','Availability','Onboarding'].map(h=><th key={h} style={{textAlign:'left',padding:'12px 18px',fontSize:11,color:'#8E8E93',textTransform:'uppercase',background:'#FAF8F4'}}>{h}</th>)}</tr></thead><tbody>{filtered.map(m=><tr key={m.id} style={{borderTop:'1px solid #ECE7DF'}}><td style={{padding:'14px 18px'}}><div style={{fontWeight:600,fontSize:13}}>{m.name}</div><div style={{fontSize:11.5,color:'#8E8E93'}}>{m.email||'No email'}</div></td><td style={{padding:'14px 18px',fontSize:12.5}}>{m.headline||'—'}{m.company?' · '+m.company:''}</td><td style={{padding:'14px 18px',fontSize:12.5}}>{m.category||'—'}</td><td style={{padding:'14px 18px'}}>★ {m.rating.toFixed(1)}</td><td style={{padding:'14px 18px'}}>{m.students}</td><td style={{padding:'14px 18px',fontSize:12}}>{m.availability||'—'}</td><td style={{padding:'14px 18px'}}><span style={{color:m.onboarding?'#166534':'#92400E',fontSize:11}}>{m.onboarding?'Complete':'Pending'}</span></td></tr>)}</tbody></table></div></Card>}</PageShell>
}

export function LivePaths(){
 const [rows,setRows]=useState<any[]>([]); const [err,setErr]=useState('')
 useEffect(()=>{getAdminPaths().then(setRows).catch(e=>setErr(e.message))},[])
 return <PageShell title="Growth Paths" subtitle="Live paths, milestones and learner progress from the Starfix database.">{err?<Card style={{padding:20,color:'#991B1B'}}>{err}</Card>:<Card style={{padding:0,overflow:'hidden'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Path','Category','Level','Milestones','Learners','Avg Progress','Rating'].map(h=><th key={h} style={{textAlign:'left',padding:'12px 18px',fontSize:11,color:'#8E8E93',textTransform:'uppercase',background:'#FAF8F4'}}>{h}</th>)}</tr></thead><tbody>{rows.map(p=><tr key={p.id} style={{borderTop:'1px solid #ECE7DF'}}><td style={{padding:'14px 18px'}}><div style={{fontWeight:600,fontSize:13}}>{p.title}</div><div style={{fontSize:11,color:'#8E8E93'}}>{p.slug}</div></td><td style={{padding:'14px 18px'}}>{p.category||'—'}</td><td style={{padding:'14px 18px'}}>{p.level||'—'}</td><td style={{padding:'14px 18px'}}>{p.milestoneCount}</td><td style={{padding:'14px 18px'}}>{p.liveLearners}</td><td style={{padding:'14px 18px',fontWeight:600}}>{p.completion}%</td><td style={{padding:'14px 18px'}}>★ {Number(p.rating||0).toFixed(1)}</td></tr>)}</tbody></table></Card>}</PageShell>
}

export function AdminHeader({profile}:{profile:any}){return <div style={{height:68,borderBottom:'1px solid #E8D9B5',background:'#FFFDF8',display:'flex',alignItems:'center',justifyContent:'flex-end',padding:'0 26px',gap:12}}><div style={{fontSize:12,color:'#737373'}}>{profile?.full_name||profile?.email}</div><button style={btn} onClick={()=>signOutAdmin().then(()=>location.reload())}>Sign out</button></div>}
