import{useEffect,useMemo,useState}from'react'
import{Card,PageShell}from'./shared'
import{getAdminOverview,getAdminUsers,getAdminMentors,getAdminPaths,getAdminExplore,getAdminAnalytics,getBookingsNamed,getConversationsNamed,type AdminUser,type AdminMentor}from'./adminBackend'

// Re-fetch live data every 30s so the admin always reflects the Starfix website.
function useLive<T>(fn:()=>Promise<T>,set:(v:T)=>void,onErr?:(m:string)=>void,ms=30000){useEffect(()=>{let on=true;const run=()=>fn().then(v=>{if(on){set(v);onErr?.('')}}).catch(e=>{if(on)onErr?.(e.message)});run();const t=setInterval(run,ms);return()=>{on=false;clearInterval(t)}},[])}
import{signIn,signOutAdmin,requireAdmin}from'./lib/supabase'

const btn={padding:'8px 13px',border:'1px solid rgba(212,175,55,0.22)',borderRadius:8,background:'rgba(255,255,255,0.05)',cursor:'pointer',fontSize:12.5,color:'#F7EFD8'}
const th={textAlign:'left' as const,padding:'14px 13px',fontSize:11.5,fontWeight:600,letterSpacing:'.03em',color:'#D4AF37',background:'rgba(212,175,55,.07)'}
const td={padding:14,borderTop:'1px solid rgba(212,175,55,.12)'}
const tones:any={green:['#4ADE80','rgba(74,222,128,.12)','rgba(74,222,128,.3)'],amber:['#FBBF24','rgba(251,191,36,.12)','rgba(251,191,36,.3)'],red:['#F87171','rgba(248,113,113,.12)','rgba(248,113,113,.3)'],gold:['#F4D67A','rgba(212,175,55,.14)','rgba(212,175,55,.35)'],gray:['#9AA0BA','rgba(255,255,255,.05)','rgba(255,255,255,.12)']}
function Pill({text,tone}:{text:string,tone:string}){const t=tones[tone]||tones.gray;return <span style={{display:'inline-block',padding:'3px 10px',borderRadius:99,fontSize:11.5,fontWeight:600,color:t[0],background:t[1],border:'1px solid '+t[2]}}>{text}</span>}
const statusTone=(x:string)=>{const v=(x||'').toLowerCase();return ['confirmed','completed'].includes(v)?'green':['pending','requested'].includes(v)?'amber':['cancelled','canceled','failed'].includes(v)?'red':'gray'}

export function AdminGate({children}:{children:React.ReactNode}){const[state,setState]=useState<'loading'|'login'|'ok'>('loading'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{requireAdmin().then(r=>{setState(r.profile?'ok':'login');if(r.error&&r.error.message!=='Not signed in')setError(r.error.message)}).catch(()=>setState('login'))},[]);if(state==='loading')return <div style={{minHeight:'100vh',display:'grid',placeItems:'center',background:'radial-gradient(circle at 50% 0%,#101A44 0%,#070A1A 55%,#04050D 100%)',color:'#D4AF37'}}>Checking administrator access…</div>;if(state==='login')return <div style={{minHeight:'100vh',display:'grid',placeItems:'center',background:'radial-gradient(circle at 50% 0%,#101A44 0%,#070A1A 55%,#04050D 100%)'}}><Card style={{width:390,maxWidth:'calc(100vw - 32px)',padding:32,background:'linear-gradient(160deg,#0E1638,#070A1A)',borderColor:'rgba(212,175,55,.38)',color:'#fff'}}><div style={{fontFamily:'Playfair Display,serif',fontSize:27}}>Starfix Admin</div><div style={{color:'#A7A7A7',fontSize:13,margin:'7px 0 24px'}}>Growth Operations · Administrator sign in</div>{error&&<div style={{background:'#351414',color:'#FCA5A5',padding:10,borderRadius:8,fontSize:12,marginBottom:14}}>{error}</div>}<input value={email}onChange={e=>setEmail(e.target.value)}placeholder="Admin email"type="email"style={{width:'100%',boxSizing:'border-box',padding:11,border:'1px solid rgba(212,175,55,.25)',background:'rgba(255,255,255,.05)',color:'#fff',borderRadius:8,marginBottom:10}}/><input value={password}onChange={e=>setPassword(e.target.value)}placeholder="Password"type="password"onKeyDown={e=>{if(e.key==='Enter')document.getElementById('admin-login')?.click()}}style={{width:'100%',boxSizing:'border-box',padding:11,border:'1px solid rgba(212,175,55,.25)',background:'rgba(255,255,255,.05)',color:'#fff',borderRadius:8}}/><button id="admin-login"disabled={busy}onClick={async()=>{setBusy(true);setError('');try{await signIn(email,password);const r=await requireAdmin();if(r.error)throw r.error;setState('ok')}catch(e){setError(e instanceof Error?e.message:'Sign in failed');await signOutAdmin()}finally{setBusy(false)}}}style={{width:'100%',marginTop:16,padding:12,border:0,borderRadius:9,background:'linear-gradient(135deg,#F4D67A,#D4AF37 55%,#B8901F)',color:'#080808',fontWeight:700,cursor:'pointer'}}>{busy?'Signing in…':'Sign in as administrator'}</button></Card></div>;return <>{children}</>}

function Stat({label,value,detail}:{label:string,value:string|number,detail:string}){return <Card style={{padding:22,position:'relative',overflow:'hidden'}}><div style={{position:'absolute',right:-30,top:-30,width:110,height:110,borderRadius:'50%',background:'radial-gradient(circle,rgba(212,175,55,.22),transparent 70%)',pointerEvents:'none'}}/><div style={{fontSize:12.5,color:'#9AA0BA',letterSpacing:'.02em'}}>{label}</div><div style={{fontFamily:'Playfair Display,serif',fontSize:38,fontWeight:600,marginTop:8,lineHeight:1.1,background:'linear-gradient(180deg,#FFF3C4,#D4AF37)',WebkitBackgroundClip:'text',backgroundClip:'text',color:'transparent'}}>{value}</div><div style={{fontSize:12,color:'#8A90AB',marginTop:8}}>{detail}</div></Card>}

function DataTable({children}:{children:React.ReactNode}){return <Card style={{padding:0,overflow:'hidden'}}><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}>{children}</table></div></Card>}

export function LiveOverview(){const[d,setD]=useState<any>(null),[err,setErr]=useState('');useEffect(()=>{getAdminOverview().then(setD).catch(e=>setErr(e.message))},[]);if(err)return <PageShell title="Overview"subtitle="Live Starfix operations."><Card style={{padding:24,color:'#F87171'}}>{err}</Card></PageShell>;if(!d)return <PageShell title="Overview"subtitle="Live Starfix operations."><Card style={{padding:24}}>Loading live Starfix data…</Card></PageShell>;return <PageShell title="Starfix Overview"subtitle="Live operational data from the Starfix Supabase database."><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:16,marginBottom:22}}><Stat label="Learners"value={d.learners}detail={d.activeLearners+' active in last 7 days'}/><Stat label="Mentor listings"value={d.mentors}detail={d.registeredMentors+' registered mentors · '+d.activeMentees+' active mentees'}/><Stat label="Bookings"value={d.bookings}detail={d.completedSessions+' completed sessions'}/><Stat label="Growth Paths"value={d.paths}detail={d.progressRecords+' live progress records'}/></div><DataTable><thead><tr>{['Mentor','Session','Status','Scheduled','Amount'].map(h=><th key={h}style={th}>{h}</th>)}</tr></thead><tbody>{d.recentBookings.length?d.recentBookings.map((b:any)=><tr key={b.id}><td style={td}>{b.mentor_name||'Mentor'}</td><td style={td}>{b.session_type||'Mentoring session'}</td><td style={td}><Pill text={b.status||'—'} tone={statusTone(b.status)}/></td><td style={td}>{b.scheduled_start?new Date(b.scheduled_start).toLocaleString():'—'}</td><td style={td}>₹{Number(b.amount||0).toLocaleString()}</td></tr>):<tr><td colSpan={5}style={{padding:28,textAlign:'center',color:'#8A90AB'}}>No bookings yet — new genuine Starfix bookings will appear here automatically.</td></tr>}</tbody></DataTable></PageShell>}

export function LiveUsers(){const[users,setUsers]=useState<AdminUser[]>([]),[q,setQ]=useState(''),[filter,setFilter]=useState('All'),[err,setErr]=useState('');useLive(getAdminUsers,setUsers,setErr);const rows=useMemo(()=>users.filter(u=>(filter==='All'||u.status===filter)&&((u.name+' '+u.email+' '+u.path).toLowerCase().includes(q.toLowerCase()))),[users,q,filter]);return <PageShell title="Learners Directory"subtitle="Real students, profile goals, live progress, XP and activity."><div style={{display:'flex',gap:10,marginBottom:16,flexWrap:'wrap'}}><input value={q}onChange={e=>setQ(e.target.value)}placeholder="Search name, email or path…"style={{flex:1,maxWidth:360,padding:10,border:'1px solid rgba(212,175,55,0.22)',borderRadius:8}}/>{['All','Active','At risk','Inactive'].map(x=><button key={x}onClick={()=>setFilter(x)}style={{...btn,background:filter===x?'linear-gradient(135deg,#F4D67A,#D4AF37)':'rgba(255,255,255,.05)',color:filter===x?'#0A0E1F':'#F7EFD8',fontWeight:filter===x?600:400}}>{x}</button>)}</div>{err?<Card style={{padding:20,color:'#F87171'}}>{err}</Card>:<DataTable><thead><tr>{['Learner','Goal','Active Path','Progress','Streak','XP','Status'].map(h=><th key={h}style={th}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map(u=><tr key={u.id}><td style={td}><b>{u.name}</b><div style={{fontSize:11,color:'#8A90AB'}}>{u.email}</div></td><td style={td}>{u.goal||'—'}</td><td style={td}>{u.path}</td><td style={td}><div style={{display:'flex',alignItems:'center',gap:8}}><div style={{width:70,height:5,borderRadius:9,background:'rgba(255,255,255,.08)'}}><div style={{width:u.progress+'%',height:'100%',borderRadius:9,background:'linear-gradient(90deg,#B8901F,#F4D67A)'}}/></div>{u.progress}%</div></td><td style={td}>{u.streak} 🔥</td><td style={td}>{u.xp.toLocaleString()}</td><td style={td}><Pill text={u.status} tone={u.status==='Active'?'green':u.status==='At risk'?'amber':'red'}/></td></tr>):<tr><td colSpan={7}style={{padding:28,textAlign:'center',color:'#8A90AB'}}>No learners match the current filter.</td></tr>}</tbody></DataTable>}</PageShell>}

export function LiveMentors(){const[rows,setRows]=useState<AdminMentor[]>([]),[q,setQ]=useState(''),[err,setErr]=useState('');useEffect(()=>{getAdminMentors().then(setRows).catch(e=>setErr(e.message))},[]);const filtered=rows.filter(m=>(m.name+' '+(m.email||'')+' '+(m.company||'')+' '+(m.category||'')).toLowerCase().includes(q.toLowerCase()));return <PageShell title="Mentors"subtitle="Live mentor records from Supabase. Learner counts and reviews are calculated from real Starfix activity, not catalog counters."><input value={q}onChange={e=>setQ(e.target.value)}placeholder="Search mentors…"style={{width:320,padding:10,border:'1px solid rgba(212,175,55,0.22)',borderRadius:8,marginBottom:16}}/>{err?<Card style={{padding:20,color:'#F87171'}}>{err}</Card>:<DataTable><thead><tr>{['Mentor','Role / Company','Category','Rating','Live mentees','Reviews','Live sessions','Status'].map(h=><th key={h}style={th}>{h}</th>)}</tr></thead><tbody>{filtered.map(m=><tr key={m.id}><td style={td}><b>{m.name}</b><div style={{fontSize:11,color:'#8A90AB'}}>{m.email||'No registered email'}</div></td><td style={td}>{m.headline||'—'}{m.company?' · '+m.company:''}</td><td style={td}>{m.category||'—'}</td><td style={td}>{m.verifiedReviewRating!==null?'★ '+m.verifiedReviewRating.toFixed(1):'—'}<div style={{fontSize:10,color:'#8A90AB'}}>{m.verifiedReviewRating!==null?'verified':'no reviews yet'}</div></td><td style={td}>{m.activeMentees}</td><td style={td}>{m.reviewCount}</td><td style={td}>{m.completedSessions}/{m.totalBookings}</td><td style={td}><Pill text={m.performanceBand} tone={m.performanceBand==='Strong live signals'?'green':m.performanceBand==='Established'?'gold':m.performanceBand==='Developing'?'amber':'gray'}/><div style={{fontSize:10,color:'#8A90AB',marginTop:4}}>{m.mentorStatus}</div></td></tr>)}</tbody></DataTable>}</PageShell>}

export function LivePaths(){const[rows,setRows]=useState<any[]>([]),[err,setErr]=useState('');useEffect(()=>{getAdminPaths().then(setRows).catch(e=>setErr(e.message))},[]);return <PageShell title="Growth Paths"subtitle="Live paths, milestones and learner progress."><DataTable>{err?<tbody><tr><td style={{padding:20,color:'#F87171'}}>{err}</td></tr></tbody>:<><thead><tr>{['Path','Category','Level','Milestones','Learners','Avg Progress','Rating'].map(h=><th key={h}style={th}>{h}</th>)}</tr></thead><tbody>{rows.map(p=><tr key={p.id}><td style={td}><b>{p.title}</b><div style={{fontSize:11,color:'#8A90AB'}}>{p.slug}</div></td><td style={td}>{p.category||'—'}</td><td style={td}>{p.level||'—'}</td><td style={td}>{p.milestoneCount}</td><td style={td}>{p.liveLearners}</td><td style={td}>{p.completion}%</td><td style={td}>★ {Number(p.rating||0).toFixed(1)}</td></tr>)}</tbody></>}</DataTable></PageShell>}

export function LiveBookings(){const[rows,setRows]=useState<any[]>([]),[q,setQ]=useState(''),[err,setErr]=useState('');useLive(getBookingsNamed,setRows,setErr);const filtered=rows.filter(b=>((b.student_name||'')+' '+b.mentor_name+' '+b.status+' '+b.session_type+' '+b.booking_date).toLowerCase().includes(q.toLowerCase()));return <PageShell title="Sessions & Bookings"subtitle="Every real Starfix mentor booking from Supabase, newest scheduled sessions first."><input value={q}onChange={e=>setQ(e.target.value)}placeholder="Search mentor, status, session…"style={{width:360,padding:10,border:'1px solid rgba(212,175,55,0.22)',borderRadius:8,marginBottom:16}}/>{err?<Card style={{padding:20,color:'#F87171'}}>{err}</Card>:<DataTable><thead><tr>{['Learner','Mentor','Session','Date / Time','Status','Amount','Notes'].map(h=><th key={h}style={th}>{h}</th>)}</tr></thead><tbody>{filtered.length?filtered.map(b=><tr key={b.id}><td style={td}><b>{b.student_name||(b.student_id?'Learner '+b.student_id.slice(0,6):'—')}</b></td><td style={td}><b>{b.mentor_name||'—'}</b><div style={{fontSize:11,color:'#8A90AB'}}>{b.mentor_company||''}</div></td><td style={td}>{b.session_type||'—'}<div style={{fontSize:11,color:'#8A90AB'}}>{b.duration||''}</div></td><td style={td}>{b.scheduled_start?new Date(b.scheduled_start).toLocaleString():b.booking_date||'—'}</td><td style={td}><Pill text={b.status||'—'} tone={statusTone(b.status)}/></td><td style={td}>₹{Number(b.amount||0).toLocaleString()}</td><td style={td}>{b.notes||'—'}</td></tr>):<tr><td colSpan={7}style={{padding:28,textAlign:'center',color:'#8A90AB'}}>No bookings yet. The table will populate from genuine student bookings.</td></tr>}</tbody></DataTable>}</PageShell>}

export function LiveExplore(){const[rows,setRows]=useState<any[]>([]),[q,setQ]=useState('');useLive(getAdminExplore,setRows);const filtered=rows.filter(x=>(x.title+' '+x.category+' '+x.content_type).toLowerCase().includes(q.toLowerCase()));return <PageShell title="Explore Content"subtitle="Real Explore resources currently stored in Starfix."><input value={q}onChange={e=>setQ(e.target.value)}placeholder="Search content…"style={{width:320,padding:10,border:'1px solid rgba(212,175,55,0.22)',borderRadius:8,marginBottom:16}}/><DataTable><thead><tr>{['Title','Category','Type','Metric','Active','Created'].map(h=><th key={h}style={th}>{h}</th>)}</tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td style={td}><b>{x.title}</b><div style={{fontSize:11,color:'#8A90AB'}}>{x.description||''}</div></td><td style={td}>{x.category}</td><td style={td}>{x.content_type}</td><td style={td}>{x.metric_value||'—'}</td><td style={td}><Pill text={x.active?'Active':'Hidden'} tone={x.active?'green':'gray'}/></td><td style={td}>{x.created_at?new Date(x.created_at).toLocaleDateString():'—'}</td></tr>)}</tbody></DataTable></PageShell>}

export function LiveMessages(){const[rows,setRows]=useState<any[]>([]);useLive(getConversationsNamed,setRows);return <PageShell title="Mentor Conversations"subtitle="Operational view of real mentor-student conversations and recent messages."><DataTable><thead><tr>{['Conversation','Learner','Mentor','Messages','Last activity','Archived'].map(h=><th key={h}style={th}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map(c=><tr key={c.id}><td style={td}>{c.id.slice(0,8)}…</td><td style={td}><b>{c.student_name||(c.student_id?'Learner '+c.student_id.slice(0,6):'—')}</b></td><td style={td}><b>{c.mentor_name||(c.mentor_id?'Mentor '+c.mentor_id.slice(0,6):'—')}</b></td><td style={td}>{c.messages?.length||0}<div style={{fontSize:11,color:'#8A90AB'}}>{c.messages?.[0]?.body?.slice(0,50)||'No messages'}</div></td><td style={td}>{c.messages?.[0]?.created_at?new Date(c.messages[0].created_at).toLocaleString():new Date(c.created_at).toLocaleString()}</td><td style={td}>{c.archived?'Yes':'No'}</td></tr>):<tr><td colSpan={6}style={{padding:28,textAlign:'center',color:'#8A90AB'}}>No conversations yet.</td></tr>}</tbody></DataTable></PageShell>}

export function LiveAnalytics(){const[d,setD]=useState<any>(null);useLive(getAdminAnalytics,setD);if(!d)return <PageShell title="Analytics"subtitle="Live Starfix metrics."><Card>Loading live analytics…</Card></PageShell>;return <PageShell title="Analytics"subtitle="Calculated directly from current Starfix database records."><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:16}}>{[['Students',d.students,'Registered student profiles'],['Registered mentors',d.mentors,d.mentorListings+' total mentor listings'],['Active mentees',d.activeMentees,'Confirmed or completed mentor relationships'],['Active 7d',d.active7,'Learners with recent activity'],['Progress',d.avgProgress+'%','Average progress'],['Completed',d.completed,'Completed progress records'],['Total XP',d.totalXp.toLocaleString(),'Across progress records'],['Bookings',d.bookings,d.confirmed+' confirmed/completed'],['Revenue','₹'+d.revenue.toLocaleString(),'Booking amount total'],['Reviews',d.reviews,'Average '+d.avgRating+'★'],['Saved Items',d.saved,'Learner saved resources'],['Notifications',d.notifications,'Notifications generated'],['Admins',d.admins,'Admin profiles']].map(([a,b,c])=><Stat key={String(a)}label={String(a)}value={b as any}detail={String(c)}/>)}</div></PageShell>}

export function AdminHeader({profile,onMenu}:{profile:any,onMenu?:()=>void}){const name=profile?.full_name||(profile?.email||'').split('@')[0]||'Administrator';return <div className="sx-header" style={{height:72,borderBottom:'1px solid rgba(212,175,55,.16)',background:'rgba(7,10,26,.72)',backdropFilter:'blur(14px)',display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 32px',gap:12,position:'sticky',top:0,zIndex:20}}><div style={{display:'flex',alignItems:'center',gap:12,minWidth:0}}><button className="sx-burger"aria-label="Open menu"onClick={onMenu}>☰</button><div style={{minWidth:0}}><div className="sx-welcome"style={{fontFamily:'Playfair Display,serif',fontSize:18,color:'#F7EFD8'}}>Welcome back, {name}</div><div className="sx-date"style={{fontSize:12,color:'#8A90AB',marginTop:2}}>{new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</div></div></div><div className="sx-hright"style={{display:'flex',alignItems:'center',gap:14}}><div style={{width:38,height:38,borderRadius:'50%',display:'grid',placeItems:'center',background:'linear-gradient(135deg,#F4D67A,#B8901F)',color:'#0A0E1F',fontWeight:700,fontFamily:'Playfair Display,serif'}}>{name.charAt(0).toUpperCase()}</div><button style={btn}onClick={()=>signOutAdmin().then(()=>location.reload())}>Sign out</button></div></div>}
